server:
  port: 8085

spring:
  application:
    name: restaurant-management
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_management_db
    #url: jdbc:postgresql://host.docker.internal:5432/restaurant_management_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: true